name: Test Clean Tree
on:
  pull_request:
jobs:
  git-clean-tree-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18     
      - name: Install yarn
        run: npm install -g yarn     
      - name: make sure package.lock does not exist
        run: rm -f package-lock.json
      - name: Check Tree if package-lock.json file was existing and removed
        run: bash ${GITHUB_WORKSPACE}/github-actions-scripts-sh/clean-tree-check.sh "removing package-lock.json file"
      - name: Install dependencies
        run: yarn
      - name: Check Tree after yarn
        run: bash ${GITHUB_WORKSPACE}/github-actions-scripts-sh/clean-tree-check.sh "yarn"
      - name: Build
        run: yarn build
      - name: Check Tree after build
        run: bash ${GITHUB_WORKSPACE}/github-actions-scripts-sh/clean-tree-check.sh "yarn build"
      - name: Clean up
        if: always()
        run: npm uninstall -g yarn